### PR TITLE
fix(core)!: resolve type inference issues with input handler

### LINKED ISSUE #1182: TypeScript error when using `S3Handler` type
**Describe the bug**

**To Reproduce**
How to reproduce the behaviour:

```ts
const lambdaHandler: S3Handler = async (event: S3Event): Promise<void> => {
  await Promise.all(event.Records.map(processRecord));
};

export const handler = middy().use(eventNormalizer()).handler(lambdaHandler);
```

```sh
Argument of type 'S3Handler' is not assignable to parameter of type 'MiddyInputHandler<S3Event, any, Context>'.
  Types of parameters 'callback' and 'opts' are incompatible.
    Type 'MiddyHandlerObject' is not assignable to type 'Callback<void>'.
      Type 'MiddyHandlerObject' provides no match for the signature '(error?: string | Error | null | undefined, result?: void | undefined): void'.
```

**Expected behaviour**

**Environment (please complete the following information):**

- Node.js: [e.g. 20]
- Middy: [e.g. 5.0.0]
- AWS SDK [e.g. 3.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by naorpeled**
fixes #1182

### CODE REVIEW

File: packages/core/index.d.ts [hunk 1]
```diff
@@ -96,12 +96,13 @@ export interface MiddyfiedHandler<
...
   after: AttachMiddlewareFn<TEvent, TResult, TErr, TContext, TInternal>
   onError: AttachMiddlewareFn<TEvent, TResult, TErr, TContext, TInternal>
-  handler: <TAdditional>(
+  handler: <TInputHandlerEventProps, TInputHandlerResultProps>(
     handler: MiddlewareHandler<
-    LambdaHandler<TEvent & TAdditional, TResult>,
+    LambdaHandler<TInputHandlerEventProps, TInputHandlerResultProps>,
     TContext
     >
-  ) => MiddyfiedHandler<TEvent, TResult, TErr, TContext, TInternal>
```
Comment (naorpeled) [inline packages/core/index.d.ts:104]: @lmammino does this make sense to you? 🙏 
I believe that this is the correct behavior

File: packages/core/index.d.ts [hunk 2]
```diff
@@ -96,12 +96,13 @@ export interface MiddyfiedHandler<
...
+    | LambdaHandler<TInputHandlerEventProps, TInputHandlerResultProps>
+  ) => MiddyfiedHandler<TInputHandlerEventProps, TInputHandlerResultProps, TErr, TContext, TInternal>
```
Comment (naorpeled) [inline packages/core/index.d.ts:105]: @lmammino does this return type make sense to you? 🙏 
I'd expect it to be taken from the input handler (`.handler<..params>`) fn and not the initial input (`middy<...params>`).

**Comment by naorpeled** [comment]
@lmammino bumping this 🙏

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
LGTM! Thanks a mill @naorpeled !

@willfarrell can I leave it to you to merge and release based on your priorities?

**Comment by jlarmstrongiv** [comment]
I think this broke the types in my project, as I’m now getting the error:

```
Binding element 'headers' implicitly has an 'any' type.
```

Whereas downgrading to `5.4.1` properly types the headers as:

```
headers: APIGatewayProxyEventHeaders | (APIGatewayProxyEventHeaders & ALBEventHeaders)
```

instead of `any`

**Comment by naorpeled** [comment]
> I think this broke the types in my project, as I’m now getting the error:
> 
> ```
> Binding element 'headers' implicitly has an 'any' type.
> ```
> 
> Whereas downgrading to `5.4.1` properly types the headers as:
> 
> ```
> headers: APIGatewayProxyEventHeaders | (APIGatewayProxyEventHeaders & ALBEventHeaders)
> ```
> 
> instead of `any`

Hey @jlarmstrongiv,
can you please share a reproduction to your issue?

**Comment by jlarmstrongiv** [comment]
Sure, here is the reproduction @naorpeled I removed the middleware to keep the reproduction as simple as possible https://github.com/jlarmstrongiv/middy-typescript-headers-bug 👍

**Comment by naorpeled** [comment]
> Sure, here is the reproduction @naorpeled I removed the middleware to keep the reproduction as simple as possible https://github.com/jlarmstrongiv/middy-typescript-headers-bug 👍
> 
> You will be able to see how `5.4.1` works, while `5.4.2` causes type errors.

I see, what you need to do is pass the generic params into `.handler` and that would resolve your issue

**Comment by jlarmstrongiv** [comment]
Hey @naorpeled do you have an example of passing those generic params into `.handler`?  It’s still erroring with the same error for me:

```ts
export const handler = middy.handler<
  APIGatewayProxyEventV2,
  APIGatewayProxyResultV2
  // Binding element 'headers' implicitly has an 'any' type.
>(({ headers }) => ({
  body: JSON.stringify(headers, undefined, 2),
  statusCode: 200,
}));
```

I also wish I could define it once with middy core like I used to, rather than having to define it on each and every lambda function handler
