### PR TITLE
Http header normaliser to lowercase

### LINKED ISSUE #166: lowercase headers by default in httpHeaderNormalizer middleware
I found out in multiple instances that "normalized" header names tend to be confusing and unexpected for developers. This is probably because most of the famous web frameworks in the JS landscape prefer to use a lowercased version of the headers name.

Although this would be a breaking change I would say that's an ideal change for version 1.0

We might still optionally produce a hashmap of "normalized" headers based on a boolean flag (but I would set that as `false` by default, to avoid extra computation when not explicitly needed).

As part of this issue, we should take care of updating all the other middlewares that rely on headers.

### PR DESCRIPTION
**Pull request by miki79**
Modified the middleware "http-header-normalizer" to normalise to lowercase. There is an extra options now in the middleware, so you can decide to normalise to camelCase.

Modified the other middleware:
- cors
- http-content-negotiation
- http-json-body-parser
- http-urlencode-body-parser

to handle headers in lowercase or camel case.

  - [x] I added tests for my changes
  - [x] I updated the documentation to reflect my changes
  - [x] I updated the Typescript typings to reflect my changes
 
I didn't updated the documentation of the middlewares about the handling of both format of header, but I don't think it's necessary.

Closes #166

### CODE REVIEW

File: packages/http-header-normalizer/index.js [hunk 1]
```diff
@@ -49,7 +53,8 @@ module.exports = (opts) => {
   }
 
   const defaults = {
-    normalizeHeaderKey
+    normalizeHeaderKey,
+    camelCase: false
```
Comment (lmammino) [inline packages/http-header-normalizer/index.js]: can we rename this `camelCase` option to canonical?

It isn't really camel case since it will also have dashes (`-` ) in between

**Comment by miki79** [comment]
yeah, I'm not very great with names, that's why I called camelCase. I changed now to canonical. Let me know if there is anything else you want me to change
