### PR TITLE
TypeScript: Align types with aws-lambda

### LINKED ISSUE #703: TypeScript: aws-lambda Handler type error
What are the steps to reproduce this issue?
-------------------------------------------
1. Defined a handler using `Handler` type from `aws-lambda`
2. Middify it:
```ts
// handler.ts
import middy from '@middy/core';
import type { Handler } from 'aws-lambda';

const handler: Handler = () => {};

export const main = middy(handler);
```

What happens?
-------------
You get a type error:

```
Argument of type 'Handler<any, any>' is not assignable to parameter of type '(event: any, context: Context) => Promise<any>'. ts(2345)
```

What were you expecting to happen?
----------------------------------
Any valid `Handler` type is accepted by `middy`.

Any other comments?
-------------------
It seems the changes in #696 don't fully wrap the `Handler` type from `aws-lambda`.
Specifically, the `callback` parameter is missing, and `void` is not in the return type.

`Handler` from `aws-lambda`:
```ts
export type Handler<TEvent = any, TResult = any> = (
    event: TEvent,
    context: Context,
    callback: Callback<TResult>,
) => void | Promise<TResult>;
```

`MiddlewareHandler` from `@middy/core`:
```ts
declare type MiddlewareHandler<THandler extends LambdaHandler<any, any>, TContext> =
  THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
    ? (event: TEvent, context: TContext) => Promise<TResult>
    : never
```

Updating the middy type to the following should work I believe:

```ts
import {
  Callback as LambdaCallback,
  Context as LambdaContext,
  Handler as LambdaHandler
} from 'aws-lambda'

// other stuff...

declare type MiddlewareHandler<THandler extends LambdaHandler<any, any>, TContext> =
  THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
    ? (event: TEvent, context: TContext, callback: LambdaCallback<TResult>) => void | Promise<TResult>
    : never
```

What versions of software are you using?
----------------------------------------
**Middy Version:** `@middy/core@2.5.0`

**TypeScript Version:** `typescript@4.3.5`

**AWS Lambda Types Version:** `@types/aws-lambda@8.10.81`

### PR DESCRIPTION
**Pull request by denovodavid**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fixes #703.
A few things have changed with the types:
1. `MiddyInputHandler` is now a copy of `Handler` from `aws-lambda` but with a generic context
2. Updated the default value of the generic context from `any` to `Context` to align it with `aws-lambda`
3. Removed typings that didn't seem necessary anymore.

Testing:
Changed the base handler to be an `aws-lambda` `Handler` type.

Any relevant logs, error output, etc?
-------------------------------------
I'm getting some lint errors from the using `void` in the return type, but that's what `aws-lambda` `Handler` uses.
How do I ignore these?
```
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard)
  .../middy/packages/core/index.d.ts:38:164: void is only valid as a return type or generic type variable (@typescript-eslint/no-invalid-void-type)
  .../middy/packages/core/index.test-d.ts:47:42: void is only valid as a return type or generic type variable (@typescript-eslint/no-invalid-void-type)
```

### CODE REVIEW

**Review by mbarton — APPROVED** [review]
Sorry for the missed case! LGTM 👍

File: packages/core/index.d.ts [hunk 1]
```diff
@@ -48,27 +48,21 @@ export interface MiddyfiedHandler<TEvent = any, TResult = any, TErr = Error, TCo
...
 
-declare type AttachMiddlewareObj<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = any> = (middleware: MiddlewareObj) => MiddyfiedHandler<TEvent, TResult, TErr, TContext>
+declare type AttachMiddlewareObj<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext> = (middleware: MiddlewareObj) => MiddyfiedHandler<TEvent, TResult, TErr, TContext>
 
-declare type UseFn<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = any> =
+declare type UseFn<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext> =
   (middlewares: MiddlewareObj<TEvent, TResult, TErr, TContext> | Array<MiddlewareObj<TEvent, TResult, TErr, TContext>>) => MiddyfiedHandler<TEvent, TResult, TErr, TContext>
 
-declare type MiddlewareHandler<THandler extends LambdaHandler<any, any>, TContext> =
-  THandler extends LambdaHandler<infer TEvent, infer TResult> // always true
```
Comment (mbarton) [inline packages/core/index.d.ts:62]: It's nice to have this type joined to the one exported from the AWS typings in some way. Maybe we can test they intersect in the typings test? Not a big deal either way given these types are very very unlikely to change

File: packages/core/index.d.ts [hunk 2]
```diff
@@ -27,17 +27,17 @@ interface Request<TEvent = any, TResult = any, TErr = Error, TContext extends La
...
 
-export interface MiddlewareObj<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = any> {
+export interface MiddlewareObj<TEvent = any, TResult = any, TErr = Error, TContext extends LambdaContext = LambdaContext> {
   before?: MiddlewareFn<TEvent, TResult, TErr, TContext>
   after?: MiddlewareFn<TEvent, TResult, TErr, TContext>
   onError?: MiddlewareFn<TEvent, TResult, TErr>
 }
 
-type MiddyInputHandler<TEvent, TResult, TContext> = (event: TEvent, context: TContext) => Promise<TResult>
+type MiddyInputHandler<TEvent, TResult, TContext extends LambdaContext = LambdaContext> = (event: TEvent, context: TContext, callback: LambdaCallback<TResult>) => void | Promise<TResult>
```
Comment (mbarton) [inline packages/core/index.d.ts:38]: I managed to suppress this locally with an eslint comment:

```suggestion
// The AWS provided Handler type uses void | Promise<TResult> so we have no choice but to follow and suppress the linter warning
// eslint-disable-next-line @typescript-eslint/no-invalid-void-type
type MiddyInputHandler<TEvent, TResult, TContext extends LambdaContext = LambdaContext> = (event: TEvent, context: TContext, callback: LambdaCallback<TResult>) => void | Promise<TResult>
```

**Review by willfarrell — APPROVED** [review]

**Comment by willfarrell** [comment]
Let me know when this is ready to go, I should be able to get a release out pretty quickly.

**Comment by denovodavid** [comment]
Thanks @mbarton I've made the appropriate changes.
@willfarrell Should be good to go 👍

**Comment by willfarrell** [comment]
Thank you! Releasing shortly.
